draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  footer_text: ""
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: â–½
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: "{mods}+ {key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_keycode_map:
    EXCLAMATION: "!"
    AT_SIGN: "@"
    HASH: "#"
    DOLLAR: $
    PERCENT: "%"
    CARET: ^
    AMPERSAND: "&"
    ASTERISK: "*"
    LEFT_PARENTHESIS: (
    RIGHT_PARENTHESIS: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    SLASH: /
    QUESTION: "?"
    BACKSLASH: \\
    PIPE: "|"
    SEMICOLON: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    DOUBLE_QUOTES: '"'
    COMMA: ","
    LESS_THAN: <
    PERIOD: .
    GREATER_THAN: ">"
    LEFT_BRACKET: "["
    LEFT_BRACE: "{"
    RIGHT_BRACKET: "]"
    RIGHT_BRACE: "}"
    GRAVE: "`"
    TILDE: "~"
    LEFT_ARROW: "LEFT"
    RIGHT_ARROW: "RIGHT"
    BACKSPACE: "BACK SPACE"
    PRINTSCREEN: "PRINT SCREEN"
  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: []
